/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libreria;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Eduardo
 */
public class DevolverLibro extends javax.swing.JFrame {

    /**
     * Creates new form LibrosE
     */
    public DevolverLibro() {
        initComponents();
    }
    
    
    
    
    //actualizar conteo de libros
    public void actualizarLibro(){
    
        int libroID = Integer.parseInt(txt_IDLibro.getText());
        
        try{
            Connection con = DBConnection.getConnection();
            String sql = "update libros_prestados_detalles set cantidad = cantidad +1 where libro_id =? ";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, libroID);
            
            int rowCount = pst.executeUpdate();
            
            if( rowCount > 0){
                JOptionPane.showMessageDialog(this," conteo de libro actualizado");
               
                
            }else{
                
                JOptionPane.showMessageDialog(this,"no se puede actualizar");
            
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
//buscar detalles de libros prestados de base de datos y mostrar en el panel
    public void LibroPrestadoDetalles(){
       
        int libroId = Integer.parseInt(txt_IDLibro.getText());
        int estudianteId = Integer.parseInt(txt_EstudianteID.getText());
        
        try {
            Connection con = DBConnection.getConnection();
            String sql = "select * from libros_prestados_detalles where libro_id = ? and estudiante_id = ? and status = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, libroId);
            pst.setInt(2, estudianteId);
            pst.setString(3 , "pendiente");
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
               
                lbl_idPrestado.setText(rs.getString("id"));
                lbl_nombreLibro1.setText(rs.getString("libro_nombre"));
                lbl_NombreEstudiante.setText(rs.getString("estudiante_nombre"));
                lbl_prestamo.setText(rs.getString("libro_prestado"));
                lbl_devolucion.setText(rs.getString("devolucion"));
                lbl_errores.setText("");
            
            }else{
                lbl_errores.setText("Ningun registro encontrado");
                lbl_idPrestado.setText("");
                lbl_nombreLibro1.setText("");
                lbl_NombreEstudiante.setText("");
                lbl_prestamo.setText("");
                lbl_devolucion.setText("");
               
            }
        }catch(Exception e){
            e.printStackTrace();
        }
       
    }
    //devolver el libro
    public boolean devolverLibro(){
        boolean estaDevuelto = false;
        
        int libroId = Integer.parseInt(txt_IDLibro.getText());
        int estudianteId = Integer.parseInt(txt_EstudianteID.getText());
        
        try{
            Connection con = DBConnection.getConnection();
            String sql = "update libros_prestados_detalles set status = ? where estudiante_id = ? and libro_id = ? and status = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, "devuelto");
            pst.setInt(2, estudianteId);
            pst.setInt(3, libroId);
            pst.setString(4, "pendiente");
            
            int rowCount = pst.executeUpdate();
            if(rowCount > 0){
                estaDevuelto = true;
            }else{
                estaDevuelto  =false;
            }
            
            
        }catch(Exception e ){
            e.printStackTrace();
        }
        return estaDevuelto;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        panel_main1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lbl_devolucion = new javax.swing.JLabel();
        lbl_idPrestado = new javax.swing.JLabel();
        lbl_nombreLibro1 = new javax.swing.JLabel();
        lbl_NombreEstudiante = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbl_errores = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lbl_prestamo = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_EstudianteID = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        rSMaterialButtonCircle2 = new necesario.RSMaterialButtonCircle();
        txt_IDLibro = new app.bolivia.swing.JCTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        rSMaterialButtonCircle3 = new necesario.RSMaterialButtonCircle();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setBackground(new java.awt.Color(255, 255, 255));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main1.setBackground(new java.awt.Color(255, 255, 255));
        panel_main1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreria/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel10.setText("Detalles de Libros");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 290, 120));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 390, 5));

        lbl_devolucion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_devolucion.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.add(lbl_devolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 190, 30));

        lbl_idPrestado.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_idPrestado.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.add(lbl_idPrestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 190, 30));

        lbl_nombreLibro1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_nombreLibro1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.add(lbl_nombreLibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 190, 30));

        lbl_NombreEstudiante.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_NombreEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.add(lbl_NombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 190, 30));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Nombre de Libro:");
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 190, 30));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Nombre del Estudiante:");
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 190, 30));

        lbl_errores.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_errores.setForeground(new java.awt.Color(255, 255, 0));
        jPanel11.add(lbl_errores, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 310, 30));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Fecha de prestamo:");
        jPanel11.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 190, 30));

        lbl_prestamo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_prestamo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.add(lbl_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 190, 30));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Fecha de Devolución:");
        jPanel11.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 190, 30));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Id de libro prestado:");
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 190, 30));

        panel_main1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 470, 670));

        jLabel11.setBackground(new java.awt.Color(255, 51, 51));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreria/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel11.setText("Devolver Libro");
        panel_main1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 350, 120));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setText("X");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        panel_main1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, -1, -1));

        txt_EstudianteID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_EstudianteID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_EstudianteID.setPlaceholder("Ingresar ID del Estudiante");
        txt_EstudianteID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_EstudianteIDFocusLost(evt);
            }
        });
        txt_EstudianteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EstudianteIDActionPerformed(evt);
            }
        });
        panel_main1.add(txt_EstudianteID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 220, 160, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreria/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N
        jLabel5.setText("ID del Estudiante:");
        panel_main1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, 170, 50));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 51, 51));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreria/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N
        jLabel30.setText("ID del Libro:");
        panel_main1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, 170, 50));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle2.setText("Devolver Libro");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        panel_main1.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 450, 350, -1));

        txt_IDLibro.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_IDLibro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_IDLibro.setPlaceholder("Ingresar ID del Libro");
        txt_IDLibro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_IDLibroFocusLost(evt);
            }
        });
        txt_IDLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDLibroActionPerformed(evt);
            }
        });
        panel_main1.add(txt_IDLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 150, 160, -1));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_main1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 120, -1, 10));

        jPanel12.setBackground(new java.awt.Color(102, 102, 255));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreria/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel9.setText("Atrás");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        panel_main1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(102, 102, 255));
        rSMaterialButtonCircle3.setText("Encontrar");
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        panel_main1.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 320, 350, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreria/icons/library-2.png"))); // NOI18N
        panel_main1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 450, 600));

        panel_main.add(panel_main1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1380, 680));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1390, 680));

        setBounds(0, 0, 1400, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_IDLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDLibroActionPerformed

    private void txt_IDLibroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_IDLibroFocusLost
           
       
    }//GEN-LAST:event_txt_IDLibroFocusLost

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        if(devolverLibro()==true){
            JOptionPane.showMessageDialog(this, "Libro devuelto exitosamente");
            actualizarLibro();
        }else{
            JOptionPane.showMessageDialog(this, "Error al intentar devolver libro");
        }
        
        
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void txt_EstudianteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EstudianteIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EstudianteIDActionPerformed

    private void txt_EstudianteIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_EstudianteIDFocusLost
       
        
    }//GEN-LAST:event_txt_EstudianteIDFocusLost

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        
        
        LibroPrestadoDetalles();
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevolverLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevolverLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevolverLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevolverLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DevolverLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_NombreEstudiante;
    private javax.swing.JLabel lbl_devolucion;
    private javax.swing.JLabel lbl_errores;
    private javax.swing.JLabel lbl_idPrestado;
    private javax.swing.JLabel lbl_nombreLibro1;
    private javax.swing.JLabel lbl_prestamo;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_main1;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private app.bolivia.swing.JCTextField txt_EstudianteID;
    private app.bolivia.swing.JCTextField txt_IDLibro;
    // End of variables declaration//GEN-END:variables
}
